version: '3.7'

services:
  pushgateway:
    image: ${IMAGE_NAME:-prom/pushgateway}:${IMAGE_TAG:-latest}
    command:
      - --web.listen-address=:${PORT}
      - --web.telemetry-path=${METRICS_PATH}
      - --web.external-url=https://${PUBLIC_HOSTNAME}${PUSHGATEWAY_PATH}
      - --web.route-prefix=/
      - --persistence.file=${DATA_PATH}/metrics
      - --persistence.interval=${PERSISTENCE_INTERVAL}
      - --log.level=${LOG_LEVEL}
    networks:
      monitoring-net:
      traefik-net:
    volumes:
      - pushgateway-data-vol:${DATA_PATH}
    healthcheck:
      test: wget --spider -q http://localhost:${PORT}${PUSHGATEWAY_PATH}/metrics
      interval: ${HEALTHCHECK_INTERVAL:-1m}
      timeout: ${HEALTHCHECK_TIMEOUT:-30s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-3m}  
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: 'true'
        traefik.http.routers.pushgateway.entrypoints: http
        traefik.http.routers.pushgateway.rule: Host(`${PUBLIC_HOSTNAME}`) && PathPrefix(`${PUSHGATEWAY_PATH}`)
        traefik.http.services.pushgateway.loadbalancer.server.port: '${PORT}'
        traefik.http.middlewares.pushgateway-auth.basicauth.users: ${UI_AUTH}
        traefik.http.middlewares.pushgateway-stripprefix.stripprefix.prefixes: ${PUSHGATEWAY_PATH}
        traefik.http.routers.pushgateway.middlewares: pushgateway-auth,pushgateway-stripprefix
        traefik.http.routers.pushgateway.service: pushgateway
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-16M}

networks:
  monitoring-net:
    name: ${MONITORING_NET_NAME:-monitoring-net}
    driver: ${MONITORING_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

volumes:
  pushgateway-data-vol:
    name: ${PUSHGATEWAY_DATA_VOL_NAME:-pushgateway-data-vol}

